In [1]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [2]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[7 7]
 [7 7]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.65236006  0.12400089]
 [ 0.17844184  0.80050493]]


In [4]:
import numpy as np 
a = 'hello world' 
print (a)

hello world


In [5]:
import numpy as np 
a = np.array([1,2,3]) 
print (a)

[1 2 3]


In [6]:
# more than one dimensions 
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print (a)

[[1 2]
 [3 4]]


In [7]:
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print (a)

[[1 2 3 4 5]]


In [8]:
# dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print (a)

[ 1.+0.j  2.+0.j  3.+0.j]


In [9]:
# using array-scalar type 
import numpy as np 
dt = np.dtype(np.int32) 
print (dt)

int32


In [10]:
import numpy as np 

dt = np.dtype('i4')
print (dt)

int32


In [11]:
import numpy as np 
dt = np.dtype('>i4') 
print (dt)

>i4


In [12]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print (a)

[(b'abc', 21,  50.) (b'xyz', 18,  75.)]


In [13]:
import numpy as np 
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
print (student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [14]:
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print (a['age'])

[10 20 30]


In [15]:
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print (a)

[(10,) (20,) (30,)]


In [16]:
import numpy as np 
dt = np.dtype([('age',np.int8)]) 
print (dt) 

[('age', 'i1')]
